spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/photoz_clone
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB