spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/photoz_clone
    username: admin
    password: admin
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${clientId}
            clientSecret: ${clientSecret}
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile
springdoc:
  swagger-ui:
    oauth:
      clientId: ${clientId}
      clientSecret: ${clientSecret}
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html